# Agent prompts for zh — reuse English prompts as-is
from memory_layer.prompts.en.agent_prompts import (
    AGENT_TOOL_PRE_COMPRESS_PROMPT,
    AGENT_CASE_FILTER_PROMPT,
    AGENT_CASE_COMPRESS_PROMPT,
    AGENT_SKILL_SUCCESS_EXTRACT_PROMPT,
    AGENT_SKILL_FAILURE_EXTRACT_PROMPT,
    AGENT_SKILL_RELEVANCE_VERIFY_PROMPT,
    AGENT_SKILL_MATURITY_SCORE_PROMPT,
    AGENT_CLUSTER_LLM_ASSIGN_PROMPT,
)

__all__ = [
    "AGENT_TOOL_PRE_COMPRESS_PROMPT",
    "AGENT_CASE_FILTER_PROMPT",
    "AGENT_CASE_COMPRESS_PROMPT",
    "AGENT_SKILL_SUCCESS_EXTRACT_PROMPT",
    "AGENT_SKILL_FAILURE_EXTRACT_PROMPT",
    "AGENT_SKILL_RELEVANCE_VERIFY_PROMPT",
    "AGENT_SKILL_MATURITY_SCORE_PROMPT",
    "AGENT_CLUSTER_LLM_ASSIGN_PROMPT",
]
